Modif bdd
nantral-platform/nantralPlatform pull request #272
Opened 2021-07-04 19:04 UTC by hydrielax

2021-07-04 21:59 UTC, unitrium requested changes
Il y a quelques petits trucs à changer avant d'envoyer sur master.
Je dois avouer je suis pas tout à fait sûr que tout va marcher, est ce que tu as testé toutes les fonctionalités ? Peut-être que ce serait bien de rajouter quelques unit tests pour celles qui n'en ont pas ?

2021-07-04 21:59 UTC, unitrium commented on server/apps/club/models.py
> -if settings.DEBUG:
Si tu retires le DEBUG ici qu'est ce qui assure la difference de fonctionnement entre local et prod ?

2021-07-04 21:59 UTC, unitrium commented on server/apps/group/forms.py
> +    if group==Club:
Ça marche ça ?
Je pense pas que ça va marcher, group est une instance de quelque chose Club est une classe ce n'est pas la même chose.
Pour faire ce que tu veux faire faut faire
```
isinstance(group, Club)
```

2021-07-04 21:59 UTC, unitrium commented on server/apps/group/forms.py
> +    elif group==BDX:
Pareil

2021-07-04 21:59 UTC, unitrium commented on server/apps/group/models.py
> -if settings.DEBUG:
Même question sur la disparition du DEBUG, qu'est ce qui assure la difference de fonctionnement entre local et prod?

2021-07-04 21:59 UTC, unitrium commented on server/apps/group/models.py
> +    resume = models.CharField('Résumé', max_length=500, null=True, blank=True)
à renommer en summary, l'idée est d'eviter les mots français dans le code

2021-07-04 21:59 UTC, unitrium commented on server/apps/event/views.py
> +        context['group_type'] = self.object.group.split('--')[0]
Je pense que ce serait mieux que group_type soit une proprité de groupe.
Cela serait beaucoup plus propre de l'appeller ainsi:
group.get_type
Je vois qu'on l'utilise plusieurs fois le split c'est du code en trop.
Il faudrait dans Group:
```
@property
def get_type(self):
   return self.classname.lower()
   ou return self.object.group.split('--')[0]
  ```
  Ou un truc dans le genre plutôt que de récrire le bout de code partout.

2021-07-04 21:59 UTC, unitrium commented on server/config/urls.py
> +#from django.conf.urls import url, include
À retirer si c'est un commentaire qui ne sert plus

2021-07-04 21:59 UTC, unitrium commented on server/apps/post/views.py
> +def edit_posts(request, group_slug, group_type):
Pareil que pour group views, group type devrait être un attribut de Groupe que tu peux récupérer en faisaint group.get_type()

2021-07-04 21:59 UTC, unitrium commented on server/apps/post/views.py
> +    def post(self, request,  group_slug, group_type):
Pareil devrait pouvoir être évité

2021-07-04 21:59 UTC, unitrium commented on server/apps/liste/models.py
> -if settings.DEBUG:
Même remarque sur le DEBUG

2021-07-04 21:59 UTC, unitrium commented on server/apps/group/views.py
> +        #groupe abstrait
Les groupes abstraits ne peuvent être instancié cela doit retourner une exception car c'est une erreur si cela arrive

2021-07-04 21:59 UTC, unitrium commented on server/config/settings/base.py
> +                "apps.group.contexts.appname",
Ça sert à quoi ? Je suis curieux de savoir ça

2021-07-05 07:13 UTC, hydrielax commented on server/apps/club/models.py
> -if settings.DEBUG:
La différence est au niveau du fichier settings : si on est en debug il règle les medias sur le dossier Media, sinon sur le serveur de fichiers pour la prod. En l'occurrence ici il n'y avait pas de différence entre le if et le else (c'était un pathandrename('group/...') dans les deux cas).

2021-07-05 07:15 UTC, hydrielax commented on server/apps/group/forms.py
> +    if group==Club:
Nope ça marchera pas, parce que j'envoie dans la variable Group la classe elle-même et non un objet de cette classe. Mais peut-être revoir pour changer ça oui

2021-07-05 07:16 UTC, hydrielax commented on server/apps/group/forms.py
> +    elif group==BDX:
Pareil du coup ;)

2021-07-05 07:16 UTC, hydrielax commented on server/apps/group/models.py
> -if settings.DEBUG:
Encore pareil ;)

2021-07-05 07:16 UTC, hydrielax commented on server/apps/group/models.py
> +    resume = models.CharField('Résumé', max_length=500, null=True, blank=True)
Bien vu, je change ça

2021-07-05 07:21 UTC, hydrielax commented on server/apps/event/views.py
> +        context['group_type'] = self.object.group.split('--')[0]
Je crois que j'y avais pensé aussi, mais dans les faits en fait on l'utiliserais pas : dans le cas que tu cites on a juste le slug du groupe, et donc utiliser une fonction get_type de groupe nécessiterait d'avoir un truc du genre
`Group.get_group_by_slug(self.object.group).get_type` ce qui serait beaucoup plus coûteux en temps de calcul
Après je vais quand même regarder si ça serait pertinent dans d'autres cas mais a priori pas trop

2021-07-05 07:22 UTC, hydrielax commented on server/config/urls.py
> +#from django.conf.urls import url, include
Oui ya pas mal de commentaires à enlever en vrai 😅

2021-07-05 07:26 UTC, hydrielax commented on server/apps/post/views.py
> +def edit_posts(request, group_slug, group_type):
Yep non en fait, group_type et group_slug changent en fonction de comment tu accèdes à l'url :
* si tu accès par l'adresse /group/club--nom-du-club/, on a group_slug = "club--nom-du-club" et group_type="group"
* si tu y accèdes par /club/nom-du-club/, on a group_slug="nom-du-club" et group_type="club"
Avoir les deux permets de faire la différence entre ces 2 cas

2021-07-05 07:27 UTC, hydrielax commented on server/apps/post/views.py
> +    def post(self, request,  group_slug, group_type):
Bah pareil non du coup, désolé... C'est la méthode la plus simple que j'ai trouvé pour éviter de surcharger le code pour pouvoir prendre en compte les deux systèmes d'urls

2021-07-05 07:29 UTC, hydrielax commented on server/apps/group/views.py
> +        #groupe abstrait
Enfait si group_type="group" ou null, ça signifie juste que l'url est au format /group/club--nom-du-club, et donc que le slug est déjà complet. Le group_type ne sert pas à aller chercher la classe

2021-07-05 07:37 UTC, unitrium commented on server/apps/club/models.py
> -if settings.DEBUG:
Ok ca marche j'avais pas vu ca, a priori cela ne cause pas de changement dans les migrations donc cela devrait aller.

2021-07-05 07:41 UTC, hydrielax commented on server/apps/event/views.py
> +        context['group_type'] = self.object.group.split('--')[0]
Ouaip j'ai vérifié le code et on l'utilise que dans les vues de posts et d'events, et 1 fois à chaque fois, donc le mieux serait d'ajouter une méthode pour les classes Event et Post mais l'intérêt est limité du coup...

2021-07-05 07:44 UTC, hydrielax commented on server/config/settings/base.py
> +                "apps.group.contexts.appname",
Ça permet d'accéder directement au nom de l'appli dans laquelle tu es dans le template. C'est la méthode que j'utilisais avant d'utiliser group_type et group_slug dans chaque context, mais j'ai abandonné l'idée parce que ça nécessitait plein d'autres changements derrière

2021-07-05 07:50 UTC, unitrium commented on server/apps/post/views.py
> +def edit_posts(request, group_slug, group_type):
Oui mais tu pourrais avoir le group type directement contenu dans l'objet que tu vas manipuler.
Ce serait preferable car sinon tu prends le risque d'avoir un decouplage entre ton objet et ton url.
Imagine que pour une raison ou une autre tu ais /club/nom-du-club/ et ton objet sous jacent est une liste. 
Cela pourrait avoir des consequences inatendues.
Et avec le code comme ca je peux deja le faire.
Vraiment le mieux serait d'avoir group type deduit de l'objet que tu recupere quelques lignes plus loin.

2021-07-05 07:51 UTC, unitrium commented on server/apps/post/views.py
> +    def post(self, request,  group_slug, group_type):
Je vais essayer de faire quelque chose alors parce que ca me parait un peut dangereux de decoupler cela

2021-07-05 07:51 UTC, hydrielax commented on server/apps/group/forms.py
> +    if group==Club:
J'ai relu mon code du coup et en fait j'envoie dans la variable `groupe` `type(object)` afin de manipuler uniquement la classe à chaque fois. Du coup ça revient à faire un `isinstance(object)` au final mais je trouvais plus cohérent d'envoyer seulement le type de l'objet et non l'objet en entier lui-même, vu que la fonction n'en dépend pas. On peut quand même changer en faisant passer l'object dans `group` si tu préfères, et utiliser le `isinstance` derrière, à voir

2021-07-05 07:53 UTC, unitrium commented on server/apps/group/forms.py
> +    if group==Club:
Oui c'est peut-etre mieux a changer parce que dans tout le code on est parti sur le fait que group est une instance d'un group, avoir ici la classe est un peu etrange

2021-07-05 07:56 UTC, hydrielax commented on server/apps/post/views.py
> +def edit_posts(request, group_slug, group_type):
Nope, en fait l'url et l'objet sont déjà découplés à cause du fait qu'on puisse accéder à un objet par 2 urls disctinctes : /group/ et /ou /club/ dans le cas des clubs par exemples. La variable `group_type` ne désigne pas le type de l'objet, mais le chemin par lequel tu y accèdes afin de savoir comment traiter le slug récupérer (dans le premier cas le slug contient le type de l'objet, dans le second nom et donc il faudra reconstruire le slug). La variable est certes mal nommée mais j'ai pas trouvé mieux 😅

2021-07-05 07:57 UTC, hydrielax commented on server/apps/post/views.py
> +def edit_posts(request, group_slug, group_type):
En fait dans l'idéal il faudrait supprimer totalement l'accès aux objets par l'url /group/, comme ça on a une unique url par objet et c'est plus propre, mais j'ai préféré le conserver pour déboguer au cas où

2021-07-05 07:58 UTC, hydrielax commented on server/apps/post/views.py
> +    def post(self, request,  group_slug, group_type):
Cf au-dessus du coup ;)

2021-07-05 07:58 UTC, hydrielax commented on server/config/settings/base.py
> +                "apps.group.contexts.appname",
Je mets la ligne en commentaire du coup, ça pourra toujours servir si un jour on a besoin de cette fonctionnalité

2021-07-05 08:01 UTC, hydrielax commented
Pour les tests des fonctionnalités oui j'ai pu tout tester sauf le formulaire de demande d'admin car il pouvait pas se connecter au github (et j'ai pas trop pris le temps de le configurer du coup 😅)

2021-07-05 08:15 UTC, unitrium commented
Ok pas de soucis de toutes façons il semble y avoir un bug dans le système en prod depuis quelques jours puisque j'arrive pas à fermer la demande de Baptiste Pépin

2021-07-05 08:15 UTC, unitrium commented
Mais du coup parfait si tu as tout testé

2021-07-05 09:29 UTC, hydrielax commented on server/apps/group/forms.py
> +    if group==Club:
Fait !

2021-07-05 09:30 UTC, hydrielax commented on server/config/urls.py
> +#from django.conf.urls import url, include
Fait !

2021-07-06 16:27 UTC, hydrielax commented on server/apps/post/views.py
> +def edit_posts(request, group_slug, group_type):
Du coup :
- les urls en `/group/` sont supprimées
- la variable group_type est seulement utilisée dans l'url, après on se base sur l'objet lui-même

2021-07-06 16:28 UTC, hydrielax commented on server/apps/group/views.py
> +        #groupe abstrait
Du coup le cas `group_type=='group'` est supprimé (plus d'urls en group)

2021-07-06 16:30 UTC, hydrielax commented on server/apps/event/views.py
> +        context['group_type'] = self.object.group.split('--')[0]
Méthode get_type ajoutée sous la forme d'une propriété group_type
Pour le cas des events et posts en revanche le split est conservé afin de soulager la mémoire et de ne pas charger l'objet inutilement

2021-07-06 16:48 UTC, merged